### ISSUE TITLE
自然言語処理のチュートリアルをやる

### ISSUE THREAD

**Issue by akihirookuda95** [akihiro-coder/Natural-Language-Processing-with-Disaster-Tweets#1]
- 資料：[NLP Getting Started Tutorial](https://www.kaggle.com/code/philculliton/nlp-getting-started-tutorial/notebook)

**Comment by sagamixaki** [comment]
- 目的：自然減処理の手法を理解する

**Comment by sagamixaki** [comment]
- 理解していない部分もあるが、現在は重要なポイントかどうか分からないので、またあとで戻ってくる
- ひとまず次のissueに進む。
